In [7]:
class Employee:
    count = 0

    def __init__(self, name, family_name, salary, dpt):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__dpt = dpt
        Employee.count += 1

    def average_salary(employees):
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.count
class FulltimeEmployee(Employee):
    def __init__(self, name, family_name, salary, dpt):
        super().__init__(name, family_name, salary, dpt)

def main():
    employees = []
    fte1 = FulltimeEmployee("guru raghavender", "bachireddy", 1000000, "Unknown")
    employees.append(fte1)
    fte2 = FulltimeEmployee("rum", "vem", 1600000, "US")
    employees.append(fte2)
    emp1 = Employee("rocky", "num", 1400000, "Sales")
    employees.append(emp1)
    emp2 = Employee("sam", "ber", 115000, "UK")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()



Average salary: 1028750.0


In [9]:
import numpy as np
v = np.random.uniform(1,20, 20)
print(v)

v = v.reshape(4, 5)
print(v)

vec = np.where(v == np.max(v, axis=1,keepdims=True), 0, v)
print(v)

[ 9.48211414  5.34591585  3.17049622  5.52044605 12.30759639 13.15676401
 16.40320188 13.41695613  2.18898072 15.73099413  8.63428427 18.05519037
 13.58047889 10.14972725 14.17524106  4.91167447 17.17291433 10.61770814
 13.03631489  2.85626199]
[[ 9.48211414  5.34591585  3.17049622  5.52044605 12.30759639]
 [13.15676401 16.40320188 13.41695613  2.18898072 15.73099413]
 [ 8.63428427 18.05519037 13.58047889 10.14972725 14.17524106]
 [ 4.91167447 17.17291433 10.61770814 13.03631489  2.85626199]]
[[ 9.48211414  5.34591585  3.17049622  5.52044605 12.30759639]
 [13.15676401 16.40320188 13.41695613  2.18898072 15.73099413]
 [ 8.63428427 18.05519037 13.58047889 10.14972725 14.17524106]
 [ 4.91167447 17.17291433 10.61770814 13.03631489  2.85626199]]
